### PR TITLE
make-secret-available-circlCi

### PR DESCRIPTION
**Pull request by nehaabrol87**
@morrissinger This is the PR where I am trying to make the env vars available for unit and integration tests.
Now the integration tests are failing because the db is undefined.

### CODE REVIEW

**Comment by nehaabrol87** [comment]
@morrissinger  I just uncommented the tests.
These tests should pass once we add the env variables .

GM_JWT_SECRET
GM_AUTH0_DOMAIN
GM_DB
GM_PORT

**Comment by morrissinger** [comment]
Can we close this?

**Comment by nehaabrol87** [comment]
@morrissinger  This needs to be merged.
I am trying to fix a stupid issue where my integration test should give a 303 vs 200. 
Will try and fix that today.
I think it is not connecting to the right Db on the server because I see the record is there so the insert should fail.

**Comment by morrissinger** [comment]
Possible. Let's go through some of the stuff I did for robustness and intermittent unavailability of dependency microservices (i.e., Mongo).

**Comment by nehaabrol87** [comment]
sounds good.

**Comment by morrissinger** [comment]
alright

**Pull request merged**
