### PR TITLE
Adds mock telemetry

### PR DESCRIPTION
**Pull request by jonathanbarton**
This adds a way for us to repeatedly send mock telemetry data to our app, like a real balloon would. 
This will also be used to build out the /telemetry endpoint, which this expects to exist with a POST method that takes a form data object. Currently you can execute the script by navigating to /mock-telemetry and from that folder running `python rockblock.py`  -- in the future when we have implemented env variables I will store the absolute locations in there and reference instead of hardcoding to the directory.

You can run the unit tests by running `python unitttests.py` from the same folder.

### CODE REVIEW

**Comment by jonathanbarton** [comment]
Its also possible that this should live in a separate repo, but is it ok to leave here for now?

**Comment by nehaabrol87** [comment]
👍

**Comment by morrissinger** [comment]
🎈

**Comment by jonathanbarton** [comment]
just noticed I left the .pyc binaries in therr - i'll rip those out and then mergg it in. thanks guys

**Pull request merged**
